Repository charmed-hpc/charmed-hpc-terraform, pull requests merged in 2025-02, with the labels that each got.

#12 docs: add SECURITY.md
  SECURITY.md
Labels: docs

#11 feat: create module to mount an nfs server on azure
  examples/azure-managed-nfs/main.tf
  modules/azure-managed-nfs/README.md
  modules/azure-managed-nfs/main.tf
  modules/azure-managed-nfs/outputs.tf
  modules/azure-managed-nfs/variables.tf
  modules/azure-managed-nfs/versions.tf
Labels: C-terraform, feature, C-filesystem

#13 feat: add CODEOWNERS file
  .github/CODEOWNERS
Labels: C-terraform, feature

#14 feat: modularize terraform plans
  .github/workflows/ci.yaml
  README.md
  examples/slurm/main.tf
  justfile
  main.tf
  modules/azure-managed-nfs/main.tf
  modules/azure-managed-nfs/outputs.tf
  modules/azure-managed-nfs/variables.tf
  modules/slurm/README.md
  modules/slurm/main.tf
  modules/slurm/outputs.tf
  modules/slurm/variables.tf
  modules/slurm/versions.tf
  variables.tf
Labels: C-terraform, feature
